# tasks file for inverso.python-pip

- name: check required variables
  assert:
    that:
      - python_pip__package     | mandatory
      - python_pip__config_file | mandatory
      - python_pip__state       in [ 'present', 'absent', 'latest' ]
      - python_pip__modules     is iterable
  tags: ['varcheck']

- name: configure python for os
  set_fact:
    python_pip__package: 'python3-pip'
    python_pip__executable: '/usr/bin/pip3'
  when:
    - ansible_os_family | lower == 'redhat'
    - ansible_distribution_major_version == '8'

- name: set python_pip__package
  set_fact:
    python_pip__package: 'python3-pip'
  when:
    - ansible_python_interpreter is defined
    - '"3" in ansible_python_interpreter'

- name: ensure python-pip is '{{ python_pip__state }}'
  package:
    name: '{{ python_pip__package }}'
    state: "{{ python_pip__state | default('present') }}"

- name: ensure python-pip trusts root certificate
  copy: 
    dest: '{{ python_pip__config_file }}'
    content: |
      [global]
      cert = {{ python_pip__trusted_cert }}
  when: python_pip__state in ['present','latest'] and python_pip__trusted_cert

- name: ensure python-pip modules are '{{ python_pip__state }}'
  pip:
    name: '{{ python_pip__modules }}'
    state: "{{ python_pip__state | default('present')}}"
    extra_args: '{{ python_pip__args | default(omit) }}'
    executable: '{{ python_pip__executable | default(omit) }}'
  when: python_pip__modules | length > 0
