# tasks file for inverso.python-pip

- name: check required variables
  assert:
    that:
      - python_pip__package     | mandatory
      - python_pip__config_file | mandatory
      - python_pip__state       in [ 'present', 'absent', 'latest' ]
      - python_pip__modules     is iterable
  tags: ['varcheck']

#- name: configure python for os
#  set_fact:
#    python_pip__package: 'python3-pip'
#    python_pip__executable: '/usr/bin/pip3'
#  when:
#    - ansible_os_family | lower == 'redhat'
#    - ansible_distribution_major_version == '8'

#- name: set python_pip__package
#  set_fact:
#    python_pip__package: 'python3-pip'
#  when:
#    - ansible_python_interpreter is defined
#    - '"3" in ansible_python_interpreter'

- name: python-pip base configuration
  include_role:
    name: 'geerlingguy.pip'
  vars:
    pip_package: "{{ python_pip__package }}"
    pip_install_packages: '{{ python_pip__modules }}'
    #pip_executable: '{{ python_pip__executable }}'
  when:
    - python_pip__state in ['present','latest']

- name: ensure python-pip trusts root certificate
  copy: 
    dest: '{{ python_pip__config_file }}'
    content: |
      [global]
      cert = {{ python_pip__trusted_cert }}
  when:
    - python_pip__state in ['present','latest']
    - python_pip__trusted_cert != ''
