# tasks file for inverso.python-pip

- name: check required variables
  assert:
    that:
      - pip_config_file      | mandatory
      - pip_state            in [ 'present', 'absent', 'latest' ]
      - pip_install_packages is iterable
  tags: ['varcheck']

- name: python-pip base configuration
  include_role:
    name: 'geerlingguy.pip'
  when:
    - pip_state in ['present','latest']

- name: ensure python-pip trusts root certificate
  copy: 
    dest: '{{ pip_config_file }}'
    content: |
      [global]
      cert = {{ _pip_trusted_cert }}
  vars:
    _pip_trusted_cert_available:
      debian: '/etc/ssl/certs/ca-certificates.crt'
      redhat: '/etc/pki/tls/certs/ca-bundle.crt'
    _pip_trusted_cert: "{{ pip_trusted_cert | ternary( pip_trusted_cert, _pip_trusted_cert_available[ansible_os_family | lower ]) }}"
  when:
    - pip_state in ['present','latest']
    - pip_trusted_cert != ''
